---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tea
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: gcr.io/vincit-teatime/frontend-nginx:${NGINX_VERSION}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
            initialDelaySeconds: 10
            timeoutSeconds: 3
          env:
            - name: LB_IP_ADDR
              value: 35.241.44.184
        - name: gateway
          image: gcr.io/vincit-teatime/frontend-gateway:${GATEWAY_VERSION}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          # TODO: add probes
          #readinessProbe:
          #  tcpSocket:
          #    port: 3000
          #  periodSeconds: 5
          #  initialDelaySeconds: 5
          #  timeoutSeconds: 3
          #livenessProbe:
          #  tcpSocket:
          #    port: 3000
          #  periodSeconds: 5
          #  initialDelaySeconds: 10
          #  timeoutSeconds: 3
