---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tea
  name: chatapp-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatapp-gateway
  template:
    metadata:
      labels:
        app: chatapp-gateway
    spec:
      containers:
        - name: gateway
          image: IMAGE_REF
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          # TODO: add probes
