---
steps:
 
  # Build docker image
  - name: gcr.io/cloud-builders/docker
    args: [ "build", "-t", "gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:$SHORT_SHA", "$_BASE_DIR" ]

  # Push docker image to GCR
  - name: gcr.io/cloud-builders/docker
    args: [ "push", "gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:$SHORT_SHA" ]
  
  # Update image in k8s deployment manifest
  - name: busybox
    args: [ "sed", "-i", "s|IMAGE_REF|gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:$SHORT_SHA|g", "$_BASE_DIR/k8s/deployment.yaml" ]

  # Configure kubectl to talk to our cluster
  - name: gcr.io/cloud-builders/gcloud
    args: [ "container", "clusters", "get-credentials", "$_CLUSTER", "--region", "$_REGION" ]

  # Re-configure deployment
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "kubectl"
    args: [ "apply", "-f", "$_BASE_DIR/k8s/" ]

