---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  namespace: tea
  name: lets-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${ACME_EMAIL_ADDRESS}
    privateKeySecretRef:
      name: lets-prod-pk
    http01: {}
