---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tea
  name: chatservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
        - name: chatservice
          image: gcr.io/vincit-teatime/2018-chatservice:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /chattest
              port: 8080
            periodSeconds: 5
            initialDelaySeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /chattest
              port: 8080
            periodSeconds: 5
            initialDelaySeconds: 15
            timeoutSeconds: 3
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: MONGODB_URI
            - name: MONGODB_SSL
              value: "true"
            - name: MONGODB_DBNAME
              value: "chat"
            - name: _JAVA_OPTIONS
              value: "-Xss256K -Xmx192M -Xms64M -XX:MaxRAM=256M -XX:MaxMetaspaceSize=64M"

